from fastapi import FastAPI
from app.controllers.user_controller import user_router
from app.controllers.note_controller import note_router
from app.controllers.ai_controller import ai_router
from app.controllers.auth_controller import auth_router
from app.database.database import init_db

app = FastAPI(
    title="AI Knowledge Base API (Local LLM Assistant)",
    version="1.0",
    description=(
        "An API where the user can:\n\n"
        "- **Save content** (notes, articles, ideas)\n"
        "- **Ask questions** about this content\n"
        "- **Receive answers** generated by a local LLM (Ollama)"
    ),
)



@app.on_event("startup")
async def on_startup():
    await init_db()


app.include_router(user_router)
app.include_router(note_router)
app.include_router(ai_router)
app.include_router(auth_router)
